<?xml version="1.0" encoding="utf-8"?><Database Name="imageDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLExpress;Initial Catalog=imageDB;Integrated Security=True" SettingsObjectName="ISBusinessLayer.Properties.Settings" SettingsPropertyName="imageDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ISFolder" Member="ISFolders">
    <Type Name="ISFolder">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Foldername" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FolderType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ISFolder_ISFolderToISUser" Member="ISFolderToISUsers" ThisKey="ID" OtherKey="ISFolderID" Type="ISFolderToISUser" />
      <Association Name="ISFolder_ISResolutionToISFolder" Member="ISResolutionToISFolders" ThisKey="ID" OtherKey="ISFolderID" Type="ISResolutionToISFolder" />
      <Association Name="ISFolder_ISProductTypeToISFolder" Member="ISProductTypeToISFolders" ThisKey="ID" OtherKey="ISFolderID" Type="ISProductTypeToISFolder" />
      <Association Name="ISFolder_ISImage" Member="ISImages" ThisKey="ID" OtherKey="ISFolderID" Type="ISImage" />
      <Association Name="ISFolderToISUser_ISFolder" Member="ISFolderToISUser" ThisKey="ID" OtherKey="ISFolderID" Type="ISFolderToISUser" IsForeignKey="true" />
      <Association Name="ISImage_ISFolder" Member="ISImage" ThisKey="ID" OtherKey="ISFolderID" Type="ISImage" IsForeignKey="true" />
      <Association Name="ISResolutionToISFolder_ISFolder" Member="ISResolutionToISFolder" ThisKey="ID" OtherKey="ISFolderID" Type="ISResolutionToISFolder" IsForeignKey="true" />
      <Association Name="ISProductTypeToISFolder_ISFolder" Member="ISProductTypeToISFolder" ThisKey="ID" OtherKey="ISFolderID" Type="ISProductTypeToISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISFolderToISUser" Member="ISFolderToISUsers">
    <Type Name="ISFolderToISUser">
      <Column Name="connectGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISUserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISFolderToISUser_ISFolder" Member="ISFolders" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" />
      <Association Name="ISFolderToISUser_ISUser" Member="ISUsers" ThisKey="ISUserID" OtherKey="ID" Type="ISUser" />
      <Association Name="ISUser_ISFolderToISUser" Member="ISUser" ThisKey="ISUserID" OtherKey="ID" Type="ISUser" IsForeignKey="true" />
      <Association Name="ISFolder_ISFolderToISUser" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISUser" Member="ISUsers">
    <Type Name="ISUser">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PermissionLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ISUser_ISFolderToISUser" Member="ISFolderToISUsers" ThisKey="ID" OtherKey="ISUserID" Type="ISFolderToISUser" />
      <Association Name="ISFolderToISUser_ISUser" Member="ISFolderToISUser" ThisKey="ID" OtherKey="ISUserID" Type="ISFolderToISUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISResolutionToISFolder" Member="ISResolutionToISFolders">
    <Type Name="ISResolutionToISFolder">
      <Column Name="connectGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISResolutionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISResolutionToISFolder_ISFolder" Member="ISFolders" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" />
      <Association Name="ISResolutionToISFolder_ISResolution" Member="ISResolutions" ThisKey="ISResolutionID" OtherKey="ID" Type="ISResolution" />
      <Association Name="ISFolder_ISResolutionToISFolder" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
      <Association Name="ISResolution_ISResolutionToISFolder" Member="ISResolution" ThisKey="ISResolutionID" OtherKey="ID" Type="ISResolution" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISProductTypeToISFolder" Member="ISProductTypeToISFolders">
    <Type Name="ISProductTypeToISFolder">
      <Column Name="connectGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISProductTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISProductTypeToISFolder_ISFolder" Member="ISFolders" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" />
      <Association Name="ISProductTypeToISFolder_ISProductType" Member="ISProductTypes" ThisKey="ISProductTypeID" OtherKey="ID" Type="ISProductType" />
      <Association Name="ISFolder_ISProductTypeToISFolder" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
      <Association Name="ISProductType_ISProductTypeToISFolder" Member="ISProductType" ThisKey="ISProductTypeID" OtherKey="ID" Type="ISProductType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISImage" Member="ISImages">
    <Type Name="ISImage">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISImage_ISFolder" Member="ISFolders" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" />
      <Association Name="ISFolder_ISImage" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISProductType" Member="ISProductTypes">
    <Type Name="ISProductType">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ISProductType_ISProductTypeToISFolder" Member="ISProductTypeToISFolders" ThisKey="ID" OtherKey="ISProductTypeID" Type="ISProductTypeToISFolder" />
      <Association Name="ISProductTypeToISFolder_ISProductType" Member="ISProductTypeToISFolder" ThisKey="ID" OtherKey="ISProductTypeID" Type="ISProductTypeToISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISResolution" Member="ISResolutions">
    <Type Name="ISResolution">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ISResolution_ISResolutionToISFolder" Member="ISResolutionToISFolders" ThisKey="ID" OtherKey="ISResolutionID" Type="ISResolutionToISFolder" />
      <Association Name="ISResolutionToISFolder_ISResolution" Member="ISResolutionToISFolder" ThisKey="ID" OtherKey="ISResolutionID" Type="ISResolutionToISFolder" IsForeignKey="true" />
    </Type>
  </Table>
</Database>