<?xml version="1.0" encoding="utf-8"?><Database Name="imageDB" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=imageDB;Integrated Security=True" SettingsObjectName="ISBusinessLayer.Properties.Settings" SettingsPropertyName="imageDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ISFolder" Member="ISFolder">
    <Type Name="ISFolder">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Foldername" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FolderType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ISFolder_ISResolutionToISFolder" Member="ISResolutionToISFolder" ThisKey="ID" OtherKey="ISFolderID" Type="ISResolutionToISFolder" />
      <Association Name="ISFolder_ISImage" Member="ISImage" ThisKey="ID" OtherKey="ISFolderID" Type="ISImage" />
      <Association Name="ISFolder_ISProductTypeToISFolder" Member="ISProductTypeToISFolder" ThisKey="ID" OtherKey="ISFolderID" Type="ISProductTypeToISFolder" />
      <Association Name="ISFolderToISUser_ISFolder" Member="ISFolderToISUser" ThisKey="ID" OtherKey="ISFolderID" Type="ISFolderToISUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISFolderToISUser" Member="ISFolderToISUser">
    <Type Name="ISFolderToISUser">
      <Column Name="connectGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISUserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISFolderToISUser_ISFolder" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" />
      <Association Name="ISUser_ISFolderToISUser" Member="ISUser" ThisKey="ISUserID" OtherKey="ID" Type="ISUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISImage" Member="ISImage">
    <Type Name="ISImage">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISFolder_ISImage" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISProductType" Member="ISProductType">
    <Type Name="ISProductType">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ISProductTypeToISFolder_ISProductType" Member="ISProductTypeToISFolder" ThisKey="ID" OtherKey="ISProductTypeID" Type="ISProductTypeToISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISProductTypeToISFolder" Member="ISProductTypeToISFolder">
    <Type Name="ISProductTypeToISFolder">
      <Column Name="connectGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISProductTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISProductTypeToISFolder_ISProductType" Member="ISProductType" ThisKey="ISProductTypeID" OtherKey="ID" Type="ISProductType" />
      <Association Name="ISFolder_ISProductTypeToISFolder" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISResolution" Member="ISResolution">
    <Type Name="ISResolution">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ISResolutionToISFolder_ISResolution" Member="ISResolutionToISFolder" ThisKey="ID" OtherKey="ISResolutionID" Type="ISResolutionToISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISResolutionToISFolder" Member="ISResolutionToISFolder">
    <Type Name="ISResolutionToISFolder">
      <Column Name="connectGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISResolutionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ISFolderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ISResolutionToISFolder_ISResolution" Member="ISResolution" ThisKey="ISResolutionID" OtherKey="ID" Type="ISResolution" />
      <Association Name="ISFolder_ISResolutionToISFolder" Member="ISFolder" ThisKey="ISFolderID" OtherKey="ID" Type="ISFolder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISUser" Member="ISUser">
    <Type Name="ISUser">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PermissionLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ISUser_ISFolderToISUser" Member="ISFolderToISUser" ThisKey="ID" OtherKey="ISUserID" Type="ISFolderToISUser" />
    </Type>
  </Table>
</Database>