#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBusinessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using ISBusinessLayer.ConnectionClasses;
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="imageDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertISFolder(ISFolder instance);
    partial void UpdateISFolder(ISFolder instance);
    partial void DeleteISFolder(ISFolder instance);
    partial void InsertISFolderToISUser(ISFolderToISUser instance);
    partial void UpdateISFolderToISUser(ISFolderToISUser instance);
    partial void DeleteISFolderToISUser(ISFolderToISUser instance);
    partial void InsertISUser(ISUser instance);
    partial void UpdateISUser(ISUser instance);
    partial void DeleteISUser(ISUser instance);
    partial void InsertISResolutionToISFolder(ISResolutionToISFolder instance);
    partial void UpdateISResolutionToISFolder(ISResolutionToISFolder instance);
    partial void DeleteISResolutionToISFolder(ISResolutionToISFolder instance);
    partial void InsertISProductTypeToISFolder(ISProductTypeToISFolder instance);
    partial void UpdateISProductTypeToISFolder(ISProductTypeToISFolder instance);
    partial void DeleteISProductTypeToISFolder(ISProductTypeToISFolder instance);
    partial void InsertISImage(ISImage instance);
    partial void UpdateISImage(ISImage instance);
    partial void DeleteISImage(ISImage instance);
    partial void InsertISProductType(ISProductType instance);
    partial void UpdateISProductType(ISProductType instance);
    partial void DeleteISProductType(ISProductType instance);
    partial void InsertISResolution(ISResolution instance);
    partial void UpdateISResolution(ISResolution instance);
    partial void DeleteISResolution(ISResolution instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ISBusinessLayer.Properties.Settings.Default.imageDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ISFolder> ISFolders
		{
			get
			{
				return this.GetTable<ISFolder>();
			}
		}
		
		internal System.Data.Linq.Table<ISFolderToISUser> ISFolderToISUsers
		{
			get
			{
				return this.GetTable<ISFolderToISUser>();
			}
		}
		
		public System.Data.Linq.Table<ISUser> ISUsers
		{
			get
			{
				return this.GetTable<ISUser>();
			}
		}
		
		internal System.Data.Linq.Table<ISResolutionToISFolder> ISResolutionToISFolders
		{
			get
			{
				return this.GetTable<ISResolutionToISFolder>();
			}
		}
		
		internal System.Data.Linq.Table<ISProductTypeToISFolder> ISProductTypeToISFolders
		{
			get
			{
				return this.GetTable<ISProductTypeToISFolder>();
			}
		}
		
		public System.Data.Linq.Table<ISImage> ISImages
		{
			get
			{
				return this.GetTable<ISImage>();
			}
		}
		
		public System.Data.Linq.Table<ISProductType> ISProductTypes
		{
			get
			{
				return this.GetTable<ISProductType>();
			}
		}
		
		public System.Data.Linq.Table<ISResolution> ISResolutions
		{
			get
			{
				return this.GetTable<ISResolution>();
			}
		}
	}
	/*
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISFolder")]
	public partial class ISFolder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Foldername;
		
		private int _FolderType;
		
		private EntitySet<ISFolderToISUser> _ISFolderToISUsers;
		
		private EntitySet<ISResolutionToISFolder> _ISResolutionToISFolders;
		
		private EntitySet<ISProductTypeToISFolder> _ISProductTypeToISFolders;
		
		private EntitySet<ISImage> _ISImages;
		
		private EntityRef<ISFolderToISUser> _ISFolderToISUser;
		
		private EntityRef<ISImage> _ISImage;
		
		private EntityRef<ISResolutionToISFolder> _ISResolutionToISFolder;
		
		private EntityRef<ISProductTypeToISFolder> _ISProductTypeToISFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnFoldernameChanging(string value);
    partial void OnFoldernameChanged();
    partial void OnFolderTypeChanging(int value);
    partial void OnFolderTypeChanged();
    #endregion
		
		public ISFolder()
		{
			this._ISFolderToISUsers = new EntitySet<ISFolderToISUser>(new Action<ISFolderToISUser>(this.attach_ISFolderToISUsers), new Action<ISFolderToISUser>(this.detach_ISFolderToISUsers));
			this._ISResolutionToISFolders = new EntitySet<ISResolutionToISFolder>(new Action<ISResolutionToISFolder>(this.attach_ISResolutionToISFolders), new Action<ISResolutionToISFolder>(this.detach_ISResolutionToISFolders));
			this._ISProductTypeToISFolders = new EntitySet<ISProductTypeToISFolder>(new Action<ISProductTypeToISFolder>(this.attach_ISProductTypeToISFolders), new Action<ISProductTypeToISFolder>(this.detach_ISProductTypeToISFolders));
			this._ISImages = new EntitySet<ISImage>(new Action<ISImage>(this.attach_ISImages), new Action<ISImage>(this.detach_ISImages));
			this._ISFolderToISUser = default(EntityRef<ISFolderToISUser>);
			this._ISImage = default(EntityRef<ISImage>);
			this._ISResolutionToISFolder = default(EntityRef<ISResolutionToISFolder>);
			this._ISProductTypeToISFolder = default(EntityRef<ISProductTypeToISFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if ((((this._ISFolderToISUser.HasLoadedOrAssignedValue || this._ISImage.HasLoadedOrAssignedValue) 
								|| this._ISResolutionToISFolder.HasLoadedOrAssignedValue) 
								|| this._ISProductTypeToISFolder.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foldername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Foldername
		{
			get
			{
				return this._Foldername;
			}
			set
			{
				if ((this._Foldername != value))
				{
					this.OnFoldernameChanging(value);
					this.SendPropertyChanging();
					this._Foldername = value;
					this.SendPropertyChanged("Foldername");
					this.OnFoldernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderType", DbType="Int NOT NULL")]
		public int FolderType
		{
			get
			{
				return this._FolderType;
			}
			set
			{
				if ((this._FolderType != value))
				{
					this.OnFolderTypeChanging(value);
					this.SendPropertyChanging();
					this._FolderType = value;
					this.SendPropertyChanged("FolderType");
					this.OnFolderTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISFolderToISUser", Storage="_ISFolderToISUsers", ThisKey="ID", OtherKey="ISFolderID")]
		public EntitySet<ISFolderToISUser> ISFolderToISUsers
		{
			get
			{
				return this._ISFolderToISUsers;
			}
			set
			{
				this._ISFolderToISUsers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISResolutionToISFolder", Storage="_ISResolutionToISFolders", ThisKey="ID", OtherKey="ISFolderID")]
		public EntitySet<ISResolutionToISFolder> ISResolutionToISFolders
		{
			get
			{
				return this._ISResolutionToISFolders;
			}
			set
			{
				this._ISResolutionToISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISProductTypeToISFolder", Storage="_ISProductTypeToISFolders", ThisKey="ID", OtherKey="ISFolderID")]
		public EntitySet<ISProductTypeToISFolder> ISProductTypeToISFolders
		{
			get
			{
				return this._ISProductTypeToISFolders;
			}
			set
			{
				this._ISProductTypeToISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISImage", Storage="_ISImages", ThisKey="ID", OtherKey="ISFolderID")]
		public EntitySet<ISImage> ISImages
		{
			get
			{
				return this._ISImages;
			}
			set
			{
				this._ISImages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolderToISUser_ISFolder", Storage="_ISFolderToISUser", ThisKey="ID", OtherKey="ISFolderID", IsForeignKey=true)]
		public ISFolderToISUser ISFolderToISUser
		{
			get
			{
				return this._ISFolderToISUser.Entity;
			}
			set
			{
				ISFolderToISUser previousValue = this._ISFolderToISUser.Entity;
				if (((previousValue != value) 
							|| (this._ISFolderToISUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISFolderToISUser.Entity = null;
						previousValue.ISFolders.Remove(this);
					}
					this._ISFolderToISUser.Entity = value;
					if ((value != null))
					{
						value.ISFolders.Add(this);
						this._ID = value.ISFolderID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISFolderToISUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISImage_ISFolder", Storage="_ISImage", ThisKey="ID", OtherKey="ISFolderID", IsForeignKey=true)]
		public ISImage ISImage
		{
			get
			{
				return this._ISImage.Entity;
			}
			set
			{
				ISImage previousValue = this._ISImage.Entity;
				if (((previousValue != value) 
							|| (this._ISImage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISImage.Entity = null;
						previousValue.ISFolders.Remove(this);
					}
					this._ISImage.Entity = value;
					if ((value != null))
					{
						value.ISFolders.Add(this);
						this._ID = value.ISFolderID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISImage");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISResolutionToISFolder_ISFolder", Storage="_ISResolutionToISFolder", ThisKey="ID", OtherKey="ISFolderID", IsForeignKey=true)]
		public ISResolutionToISFolder ISResolutionToISFolder
		{
			get
			{
				return this._ISResolutionToISFolder.Entity;
			}
			set
			{
				ISResolutionToISFolder previousValue = this._ISResolutionToISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISResolutionToISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISResolutionToISFolder.Entity = null;
						previousValue.ISFolders.Remove(this);
					}
					this._ISResolutionToISFolder.Entity = value;
					if ((value != null))
					{
						value.ISFolders.Add(this);
						this._ID = value.ISFolderID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISResolutionToISFolder");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISProductTypeToISFolder_ISFolder", Storage="_ISProductTypeToISFolder", ThisKey="ID", OtherKey="ISFolderID", IsForeignKey=true)]
		public ISProductTypeToISFolder ISProductTypeToISFolder
		{
			get
			{
				return this._ISProductTypeToISFolder.Entity;
			}
			set
			{
				ISProductTypeToISFolder previousValue = this._ISProductTypeToISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISProductTypeToISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISProductTypeToISFolder.Entity = null;
						previousValue.ISFolders.Remove(this);
					}
					this._ISProductTypeToISFolder.Entity = value;
					if ((value != null))
					{
						value.ISFolders.Add(this);
						this._ID = value.ISFolderID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISProductTypeToISFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISFolderToISUsers(ISFolderToISUser entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = this;
		}
		
		private void detach_ISFolderToISUsers(ISFolderToISUser entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = null;
		}
		
		private void attach_ISResolutionToISFolders(ISResolutionToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = this;
		}
		
		private void detach_ISResolutionToISFolders(ISResolutionToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = null;
		}
		
		private void attach_ISProductTypeToISFolders(ISProductTypeToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = this;
		}
		
		private void detach_ISProductTypeToISFolders(ISProductTypeToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = null;
		}
		
		private void attach_ISImages(ISImage entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = this;
		}
		
		private void detach_ISImages(ISImage entity)
		{
			this.SendPropertyChanging();
			entity.ISFolder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISFolderToISUser")]
	public partial class ISFolderToISUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _connectGUID;
		
		private System.Guid _ISUserID;
		
		private System.Guid _ISFolderID;
		
		private EntitySet<ISFolder> _ISFolders;
		
		private EntitySet<ISUser> _ISUsers;
		
		private EntityRef<ISUser> _ISUser;
		
		private EntityRef<ISFolder> _ISFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnconnectGUIDChanging(System.Guid value);
    partial void OnconnectGUIDChanged();
    partial void OnISUserIDChanging(System.Guid value);
    partial void OnISUserIDChanged();
    partial void OnISFolderIDChanging(System.Guid value);
    partial void OnISFolderIDChanged();
    #endregion
		
		public ISFolderToISUser()
		{
			this._ISFolders = new EntitySet<ISFolder>(new Action<ISFolder>(this.attach_ISFolders), new Action<ISFolder>(this.detach_ISFolders));
			this._ISUsers = new EntitySet<ISUser>(new Action<ISUser>(this.attach_ISUsers), new Action<ISUser>(this.detach_ISUsers));
			this._ISUser = default(EntityRef<ISUser>);
			this._ISFolder = default(EntityRef<ISFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectGUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid connectGUID
		{
			get
			{
				return this._connectGUID;
			}
			set
			{
				if ((this._connectGUID != value))
				{
					this.OnconnectGUIDChanging(value);
					this.SendPropertyChanging();
					this._connectGUID = value;
					this.SendPropertyChanged("connectGUID");
					this.OnconnectGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISUserID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISUserID
		{
			get
			{
				return this._ISUserID;
			}
			set
			{
				if ((this._ISUserID != value))
				{
					if (this._ISUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISUserIDChanging(value);
					this.SendPropertyChanging();
					this._ISUserID = value;
					this.SendPropertyChanged("ISUserID");
					this.OnISUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISFolderID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISFolderID
		{
			get
			{
				return this._ISFolderID;
			}
			set
			{
				if ((this._ISFolderID != value))
				{
					if (this._ISFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISFolderIDChanging(value);
					this.SendPropertyChanging();
					this._ISFolderID = value;
					this.SendPropertyChanged("ISFolderID");
					this.OnISFolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolderToISUser_ISFolder", Storage="_ISFolders", ThisKey="ISFolderID", OtherKey="ID")]
		public EntitySet<ISFolder> ISFolders
		{
			get
			{
				return this._ISFolders;
			}
			set
			{
				this._ISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolderToISUser_ISUser", Storage="_ISUsers", ThisKey="ISUserID", OtherKey="ID")]
		public EntitySet<ISUser> ISUsers
		{
			get
			{
				return this._ISUsers;
			}
			set
			{
				this._ISUsers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISUser_ISFolderToISUser", Storage="_ISUser", ThisKey="ISUserID", OtherKey="ID", IsForeignKey=true)]
		public ISUser ISUser
		{
			get
			{
				return this._ISUser.Entity;
			}
			set
			{
				ISUser previousValue = this._ISUser.Entity;
				if (((previousValue != value) 
							|| (this._ISUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISUser.Entity = null;
						previousValue.ISFolderToISUsers.Remove(this);
					}
					this._ISUser.Entity = value;
					if ((value != null))
					{
						value.ISFolderToISUsers.Add(this);
						this._ISUserID = value.ID;
					}
					else
					{
						this._ISUserID = default(System.Guid);
					}
					this.SendPropertyChanged("ISUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISFolderToISUser", Storage="_ISFolder", ThisKey="ISFolderID", OtherKey="ID", IsForeignKey=true)]
		public ISFolder ISFolder
		{
			get
			{
				return this._ISFolder.Entity;
			}
			set
			{
				ISFolder previousValue = this._ISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISFolder.Entity = null;
						previousValue.ISFolderToISUsers.Remove(this);
					}
					this._ISFolder.Entity = value;
					if ((value != null))
					{
						value.ISFolderToISUsers.Add(this);
						this._ISFolderID = value.ID;
					}
					else
					{
						this._ISFolderID = default(System.Guid);
					}
					this.SendPropertyChanged("ISFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISFolderToISUser = this;
		}
		
		private void detach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISFolderToISUser = null;
		}
		
		private void attach_ISUsers(ISUser entity)
		{
			this.SendPropertyChanging();
			entity.ISFolderToISUser = this;
		}
		
		private void detach_ISUsers(ISUser entity)
		{
			this.SendPropertyChanging();
			entity.ISFolderToISUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISUser")]
	public partial class ISUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Username;
		
		private string _Password;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private string _Email;
		
		private int _PermissionLevel;
		
		private EntitySet<ISFolderToISUser> _ISFolderToISUsers;
		
		private EntityRef<ISFolderToISUser> _ISFolderToISUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnLastnameChanging(string value);
    partial void OnLastnameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPermissionLevelChanging(int value);
    partial void OnPermissionLevelChanged();
    #endregion
		
		public ISUser()
		{
			this._ISFolderToISUsers = new EntitySet<ISFolderToISUser>(new Action<ISFolderToISUser>(this.attach_ISFolderToISUsers), new Action<ISFolderToISUser>(this.detach_ISFolderToISUsers));
			this._ISFolderToISUser = default(EntityRef<ISFolderToISUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._ISFolderToISUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this.OnLastnameChanging(value);
					this.SendPropertyChanging();
					this._Lastname = value;
					this.SendPropertyChanged("Lastname");
					this.OnLastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionLevel", DbType="Int NOT NULL")]
		public int PermissionLevel
		{
			get
			{
				return this._PermissionLevel;
			}
			set
			{
				if ((this._PermissionLevel != value))
				{
					this.OnPermissionLevelChanging(value);
					this.SendPropertyChanging();
					this._PermissionLevel = value;
					this.SendPropertyChanged("PermissionLevel");
					this.OnPermissionLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISUser_ISFolderToISUser", Storage="_ISFolderToISUsers", ThisKey="ID", OtherKey="ISUserID")]
		public EntitySet<ISFolderToISUser> ISFolderToISUsers
		{
			get
			{
				return this._ISFolderToISUsers;
			}
			set
			{
				this._ISFolderToISUsers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolderToISUser_ISUser", Storage="_ISFolderToISUser", ThisKey="ID", OtherKey="ISUserID", IsForeignKey=true)]
		public ISFolderToISUser ISFolderToISUser
		{
			get
			{
				return this._ISFolderToISUser.Entity;
			}
			set
			{
				ISFolderToISUser previousValue = this._ISFolderToISUser.Entity;
				if (((previousValue != value) 
							|| (this._ISFolderToISUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISFolderToISUser.Entity = null;
						previousValue.ISUsers.Remove(this);
					}
					this._ISFolderToISUser.Entity = value;
					if ((value != null))
					{
						value.ISUsers.Add(this);
						this._ID = value.ISUserID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISFolderToISUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISFolderToISUsers(ISFolderToISUser entity)
		{
			this.SendPropertyChanging();
			entity.ISUser = this;
		}
		
		private void detach_ISFolderToISUsers(ISFolderToISUser entity)
		{
			this.SendPropertyChanging();
			entity.ISUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISResolutionToISFolder")]
	public partial class ISResolutionToISFolder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _connectGUID;
		
		private System.Guid _ISResolutionID;
		
		private System.Guid _ISFolderID;
		
		private EntitySet<ISFolder> _ISFolders;
		
		private EntitySet<ISResolution> _ISResolutions;
		
		private EntityRef<ISFolder> _ISFolder;
		
		private EntityRef<ISResolution> _ISResolution;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnconnectGUIDChanging(System.Guid value);
    partial void OnconnectGUIDChanged();
    partial void OnISResolutionIDChanging(System.Guid value);
    partial void OnISResolutionIDChanged();
    partial void OnISFolderIDChanging(System.Guid value);
    partial void OnISFolderIDChanged();
    #endregion
		
		public ISResolutionToISFolder()
		{
			this._ISFolders = new EntitySet<ISFolder>(new Action<ISFolder>(this.attach_ISFolders), new Action<ISFolder>(this.detach_ISFolders));
			this._ISResolutions = new EntitySet<ISResolution>(new Action<ISResolution>(this.attach_ISResolutions), new Action<ISResolution>(this.detach_ISResolutions));
			this._ISFolder = default(EntityRef<ISFolder>);
			this._ISResolution = default(EntityRef<ISResolution>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectGUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid connectGUID
		{
			get
			{
				return this._connectGUID;
			}
			set
			{
				if ((this._connectGUID != value))
				{
					this.OnconnectGUIDChanging(value);
					this.SendPropertyChanging();
					this._connectGUID = value;
					this.SendPropertyChanged("connectGUID");
					this.OnconnectGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISResolutionID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISResolutionID
		{
			get
			{
				return this._ISResolutionID;
			}
			set
			{
				if ((this._ISResolutionID != value))
				{
					if (this._ISResolution.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISResolutionIDChanging(value);
					this.SendPropertyChanging();
					this._ISResolutionID = value;
					this.SendPropertyChanged("ISResolutionID");
					this.OnISResolutionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISFolderID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISFolderID
		{
			get
			{
				return this._ISFolderID;
			}
			set
			{
				if ((this._ISFolderID != value))
				{
					if (this._ISFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISFolderIDChanging(value);
					this.SendPropertyChanging();
					this._ISFolderID = value;
					this.SendPropertyChanged("ISFolderID");
					this.OnISFolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISResolutionToISFolder_ISFolder", Storage="_ISFolders", ThisKey="ISFolderID", OtherKey="ID")]
		public EntitySet<ISFolder> ISFolders
		{
			get
			{
				return this._ISFolders;
			}
			set
			{
				this._ISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISResolutionToISFolder_ISResolution", Storage="_ISResolutions", ThisKey="ISResolutionID", OtherKey="ID")]
		public EntitySet<ISResolution> ISResolutions
		{
			get
			{
				return this._ISResolutions;
			}
			set
			{
				this._ISResolutions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISResolutionToISFolder", Storage="_ISFolder", ThisKey="ISFolderID", OtherKey="ID", IsForeignKey=true)]
		public ISFolder ISFolder
		{
			get
			{
				return this._ISFolder.Entity;
			}
			set
			{
				ISFolder previousValue = this._ISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISFolder.Entity = null;
						previousValue.ISResolutionToISFolders.Remove(this);
					}
					this._ISFolder.Entity = value;
					if ((value != null))
					{
						value.ISResolutionToISFolders.Add(this);
						this._ISFolderID = value.ID;
					}
					else
					{
						this._ISFolderID = default(System.Guid);
					}
					this.SendPropertyChanged("ISFolder");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISResolution_ISResolutionToISFolder", Storage="_ISResolution", ThisKey="ISResolutionID", OtherKey="ID", IsForeignKey=true)]
		public ISResolution ISResolution
		{
			get
			{
				return this._ISResolution.Entity;
			}
			set
			{
				ISResolution previousValue = this._ISResolution.Entity;
				if (((previousValue != value) 
							|| (this._ISResolution.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISResolution.Entity = null;
						previousValue.ISResolutionToISFolders.Remove(this);
					}
					this._ISResolution.Entity = value;
					if ((value != null))
					{
						value.ISResolutionToISFolders.Add(this);
						this._ISResolutionID = value.ID;
					}
					else
					{
						this._ISResolutionID = default(System.Guid);
					}
					this.SendPropertyChanged("ISResolution");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISResolutionToISFolder = this;
		}
		
		private void detach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISResolutionToISFolder = null;
		}
		
		private void attach_ISResolutions(ISResolution entity)
		{
			this.SendPropertyChanging();
			entity.ISResolutionToISFolder = this;
		}
		
		private void detach_ISResolutions(ISResolution entity)
		{
			this.SendPropertyChanging();
			entity.ISResolutionToISFolder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISProductTypeToISFolder")]
	public partial class ISProductTypeToISFolder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _connectGUID;
		
		private System.Guid _ISProductTypeID;
		
		private System.Guid _ISFolderID;
		
		private EntitySet<ISFolder> _ISFolders;
		
		private EntitySet<ISProductType> _ISProductTypes;
		
		private EntityRef<ISFolder> _ISFolder;
		
		private EntityRef<ISProductType> _ISProductType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnconnectGUIDChanging(System.Guid value);
    partial void OnconnectGUIDChanged();
    partial void OnISProductTypeIDChanging(System.Guid value);
    partial void OnISProductTypeIDChanged();
    partial void OnISFolderIDChanging(System.Guid value);
    partial void OnISFolderIDChanged();
    #endregion
		
		public ISProductTypeToISFolder()
		{
			this._ISFolders = new EntitySet<ISFolder>(new Action<ISFolder>(this.attach_ISFolders), new Action<ISFolder>(this.detach_ISFolders));
			this._ISProductTypes = new EntitySet<ISProductType>(new Action<ISProductType>(this.attach_ISProductTypes), new Action<ISProductType>(this.detach_ISProductTypes));
			this._ISFolder = default(EntityRef<ISFolder>);
			this._ISProductType = default(EntityRef<ISProductType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectGUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid connectGUID
		{
			get
			{
				return this._connectGUID;
			}
			set
			{
				if ((this._connectGUID != value))
				{
					this.OnconnectGUIDChanging(value);
					this.SendPropertyChanging();
					this._connectGUID = value;
					this.SendPropertyChanged("connectGUID");
					this.OnconnectGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISProductTypeID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISProductTypeID
		{
			get
			{
				return this._ISProductTypeID;
			}
			set
			{
				if ((this._ISProductTypeID != value))
				{
					if (this._ISProductType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISProductTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ISProductTypeID = value;
					this.SendPropertyChanged("ISProductTypeID");
					this.OnISProductTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISFolderID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISFolderID
		{
			get
			{
				return this._ISFolderID;
			}
			set
			{
				if ((this._ISFolderID != value))
				{
					if (this._ISFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISFolderIDChanging(value);
					this.SendPropertyChanging();
					this._ISFolderID = value;
					this.SendPropertyChanged("ISFolderID");
					this.OnISFolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISProductTypeToISFolder_ISFolder", Storage="_ISFolders", ThisKey="ISFolderID", OtherKey="ID")]
		public EntitySet<ISFolder> ISFolders
		{
			get
			{
				return this._ISFolders;
			}
			set
			{
				this._ISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISProductTypeToISFolder_ISProductType", Storage="_ISProductTypes", ThisKey="ISProductTypeID", OtherKey="ID")]
		public EntitySet<ISProductType> ISProductTypes
		{
			get
			{
				return this._ISProductTypes;
			}
			set
			{
				this._ISProductTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISProductTypeToISFolder", Storage="_ISFolder", ThisKey="ISFolderID", OtherKey="ID", IsForeignKey=true)]
		public ISFolder ISFolder
		{
			get
			{
				return this._ISFolder.Entity;
			}
			set
			{
				ISFolder previousValue = this._ISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISFolder.Entity = null;
						previousValue.ISProductTypeToISFolders.Remove(this);
					}
					this._ISFolder.Entity = value;
					if ((value != null))
					{
						value.ISProductTypeToISFolders.Add(this);
						this._ISFolderID = value.ID;
					}
					else
					{
						this._ISFolderID = default(System.Guid);
					}
					this.SendPropertyChanged("ISFolder");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISProductType_ISProductTypeToISFolder", Storage="_ISProductType", ThisKey="ISProductTypeID", OtherKey="ID", IsForeignKey=true)]
		public ISProductType ISProductType
		{
			get
			{
				return this._ISProductType.Entity;
			}
			set
			{
				ISProductType previousValue = this._ISProductType.Entity;
				if (((previousValue != value) 
							|| (this._ISProductType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISProductType.Entity = null;
						previousValue.ISProductTypeToISFolders.Remove(this);
					}
					this._ISProductType.Entity = value;
					if ((value != null))
					{
						value.ISProductTypeToISFolders.Add(this);
						this._ISProductTypeID = value.ID;
					}
					else
					{
						this._ISProductTypeID = default(System.Guid);
					}
					this.SendPropertyChanged("ISProductType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISProductTypeToISFolder = this;
		}
		
		private void detach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISProductTypeToISFolder = null;
		}
		
		private void attach_ISProductTypes(ISProductType entity)
		{
			this.SendPropertyChanging();
			entity.ISProductTypeToISFolder = this;
		}
		
		private void detach_ISProductTypes(ISProductType entity)
		{
			this.SendPropertyChanging();
			entity.ISProductTypeToISFolder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISImage")]
	public partial class ISImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Name;
		
		private System.Guid _ISFolderID;
		
		private EntitySet<ISFolder> _ISFolders;
		
		private EntityRef<ISFolder> _ISFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnISFolderIDChanging(System.Guid value);
    partial void OnISFolderIDChanged();
    #endregion
		
		public ISImage()
		{
			this._ISFolders = new EntitySet<ISFolder>(new Action<ISFolder>(this.attach_ISFolders), new Action<ISFolder>(this.detach_ISFolders));
			this._ISFolder = default(EntityRef<ISFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISFolderID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ISFolderID
		{
			get
			{
				return this._ISFolderID;
			}
			set
			{
				if ((this._ISFolderID != value))
				{
					if (this._ISFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnISFolderIDChanging(value);
					this.SendPropertyChanging();
					this._ISFolderID = value;
					this.SendPropertyChanged("ISFolderID");
					this.OnISFolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISImage_ISFolder", Storage="_ISFolders", ThisKey="ISFolderID", OtherKey="ID")]
		public EntitySet<ISFolder> ISFolders
		{
			get
			{
				return this._ISFolders;
			}
			set
			{
				this._ISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISFolder_ISImage", Storage="_ISFolder", ThisKey="ISFolderID", OtherKey="ID", IsForeignKey=true)]
		public ISFolder ISFolder
		{
			get
			{
				return this._ISFolder.Entity;
			}
			set
			{
				ISFolder previousValue = this._ISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISFolder.Entity = null;
						previousValue.ISImages.Remove(this);
					}
					this._ISFolder.Entity = value;
					if ((value != null))
					{
						value.ISImages.Add(this);
						this._ISFolderID = value.ID;
					}
					else
					{
						this._ISFolderID = default(System.Guid);
					}
					this.SendPropertyChanged("ISFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISImage = this;
		}
		
		private void detach_ISFolders(ISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISImage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISProductType")]
	public partial class ISProductType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Name;
		
		private System.Nullable<double> _Price;
		
		private EntitySet<ISProductTypeToISFolder> _ISProductTypeToISFolders;
		
		private EntityRef<ISProductTypeToISFolder> _ISProductTypeToISFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPriceChanging(System.Nullable<double> value);
    partial void OnPriceChanged();
    #endregion
		
		public ISProductType()
		{
			this._ISProductTypeToISFolders = new EntitySet<ISProductTypeToISFolder>(new Action<ISProductTypeToISFolder>(this.attach_ISProductTypeToISFolders), new Action<ISProductTypeToISFolder>(this.detach_ISProductTypeToISFolders));
			this._ISProductTypeToISFolder = default(EntityRef<ISProductTypeToISFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._ISProductTypeToISFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISProductType_ISProductTypeToISFolder", Storage="_ISProductTypeToISFolders", ThisKey="ID", OtherKey="ISProductTypeID")]
		public EntitySet<ISProductTypeToISFolder> ISProductTypeToISFolders
		{
			get
			{
				return this._ISProductTypeToISFolders;
			}
			set
			{
				this._ISProductTypeToISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISProductTypeToISFolder_ISProductType", Storage="_ISProductTypeToISFolder", ThisKey="ID", OtherKey="ISProductTypeID", IsForeignKey=true)]
		public ISProductTypeToISFolder ISProductTypeToISFolder
		{
			get
			{
				return this._ISProductTypeToISFolder.Entity;
			}
			set
			{
				ISProductTypeToISFolder previousValue = this._ISProductTypeToISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISProductTypeToISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISProductTypeToISFolder.Entity = null;
						previousValue.ISProductTypes.Remove(this);
					}
					this._ISProductTypeToISFolder.Entity = value;
					if ((value != null))
					{
						value.ISProductTypes.Add(this);
						this._ID = value.ISProductTypeID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISProductTypeToISFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISProductTypeToISFolders(ISProductTypeToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISProductType = this;
		}
		
		private void detach_ISProductTypeToISFolders(ISProductTypeToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISProductType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISResolution")]
	public partial class ISResolution : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private int _Width;
		
		private int _Height;
		
		private EntitySet<ISResolutionToISFolder> _ISResolutionToISFolders;
		
		private EntityRef<ISResolutionToISFolder> _ISResolutionToISFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnWidthChanging(int value);
    partial void OnWidthChanged();
    partial void OnHeightChanging(int value);
    partial void OnHeightChanged();
    #endregion
		
		public ISResolution()
		{
			this._ISResolutionToISFolders = new EntitySet<ISResolutionToISFolder>(new Action<ISResolutionToISFolder>(this.attach_ISResolutionToISFolders), new Action<ISResolutionToISFolder>(this.detach_ISResolutionToISFolders));
			this._ISResolutionToISFolder = default(EntityRef<ISResolutionToISFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._ISResolutionToISFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Width", DbType="Int NOT NULL")]
		public int Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				if ((this._Width != value))
				{
					this.OnWidthChanging(value);
					this.SendPropertyChanging();
					this._Width = value;
					this.SendPropertyChanged("Width");
					this.OnWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Int NOT NULL")]
		public int Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISResolution_ISResolutionToISFolder", Storage="_ISResolutionToISFolders", ThisKey="ID", OtherKey="ISResolutionID")]
		public EntitySet<ISResolutionToISFolder> ISResolutionToISFolders
		{
			get
			{
				return this._ISResolutionToISFolders;
			}
			set
			{
				this._ISResolutionToISFolders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ISResolutionToISFolder_ISResolution", Storage="_ISResolutionToISFolder", ThisKey="ID", OtherKey="ISResolutionID", IsForeignKey=true)]
		public ISResolutionToISFolder ISResolutionToISFolder
		{
			get
			{
				return this._ISResolutionToISFolder.Entity;
			}
			set
			{
				ISResolutionToISFolder previousValue = this._ISResolutionToISFolder.Entity;
				if (((previousValue != value) 
							|| (this._ISResolutionToISFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ISResolutionToISFolder.Entity = null;
						previousValue.ISResolutions.Remove(this);
					}
					this._ISResolutionToISFolder.Entity = value;
					if ((value != null))
					{
						value.ISResolutions.Add(this);
						this._ID = value.ISResolutionID;
					}
					else
					{
						this._ID = default(System.Guid);
					}
					this.SendPropertyChanged("ISResolutionToISFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ISResolutionToISFolders(ISResolutionToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISResolution = this;
		}
		
		private void detach_ISResolutionToISFolders(ISResolutionToISFolder entity)
		{
			this.SendPropertyChanging();
			entity.ISResolution = null;
		}
	}*/
}
#pragma warning restore 1591
